

spring:
  application:
    name: edulearn
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JDBC_DATASOURCE_URL}
    username: ${JDBC_DATASOURCE_USERNAME}
    password: ${JDBC_DATASOURCE_PASSWORD}

  jpa:
    show-sql: true
    hibernate :
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  ai:
    openai.api-key: ${OPENAI_API_KEY}
  mail:
    host: ${MAIL_URL}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          smtp:
            starttls:
              enable: true
cloudinary:
  cloud-name: ${CLOUDINARY_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}